// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wFNY66qT5Ir0q3quEcUFlK5CfxZDVmc',
    appId: '1:626014583444:web:ed38103aa3b81230f6d281',
    messagingSenderId: '626014583444',
    projectId: 'cp-foodies',
    authDomain: 'cp-foodies.firebaseapp.com',
    storageBucket: 'cp-foodies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLS50khhO1R_hpFHR2Ardd_qZS9xCR2nE',
    appId: '1:626014583444:android:e2d75eb4b1becca2f6d281',
    messagingSenderId: '626014583444',
    projectId: 'cp-foodies',
    storageBucket: 'cp-foodies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDegrwdi7anSm5tBY_DP1NNnfZb50MmuEo',
    appId: '1:626014583444:ios:e61cff2c3a1b9f87f6d281',
    messagingSenderId: '626014583444',
    projectId: 'cp-foodies',
    storageBucket: 'cp-foodies.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDegrwdi7anSm5tBY_DP1NNnfZb50MmuEo',
    appId: '1:626014583444:ios:6312291ebc956f7ef6d281',
    messagingSenderId: '626014583444',
    projectId: 'cp-foodies',
    storageBucket: 'cp-foodies.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
